[manifest]
id = "de_v10lator_ger"
version = "1.3.0"
display_name = "German mod"
description = "Deutsch"
short_description = "Deutsch"
authors = [ "V10lator" ]
game_id = "bk"
minimum_recomp_version = "1.0.1"
dependencies = [ "bk_recomp_asset_expansion_pak:0.0.3" ]
conflicts = [ "font_plus_latin_1" ]
optional_dependencies = [ "font_plus_latin_1" ]
native_libraries = []

[inputs]
elf_path = "build/mod.elf"
mod_filename = "german"
func_reference_syms_file = "BanjoRecompSyms/bk.us.rev0.syms.toml"
data_reference_syms_files = [ "BanjoRecompSyms/bk.us.rev0.datasyms.toml" ]
additional_files = [ "thumb.png" ]
